server:
  baseUrl: http://localhost:3000/
  imageUrl: images/
  imageServerDir: c:/images/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:8080/
  imageUrl: product/images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/
